### ISSUE TITLE
wiki - clarify - the mapping analysis  example

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/ALPPACA#101]
Mapping analysis   example
R2 example is = R1 example : --R2 "*_2.fastq.gz" ? 

A bit confusing also in the example: --suffix (extension ?)  fastq.gz why the _1 or should we only indicate extension for read 1 ?

**Comment by hkaspersen** [comment]
Not quite sure what you mean on the R2 example? This is different based on the user input, but both need to be supplied. 

For the --suffix, this string is used to generate the sample name common for both R1 and R2 from the R1 filename. Thus, only the suffix for the R1 will need to be supplied. It might be that I will update this to make it easier at a later date, but for now this is done due to the nature of the Snippy multi functionality.
