### ISSUE TITLE
Switch from Prokka to Bakta

### ISSUE THREAD

**Issue by hkaspersen** [NorwegianVeterinaryInstitute/ALPPACA#54]
Bakta is significantly faster than prokka, and is currently being actively worked on and improved.

**Comment by hkaspersen** [comment]
Need to add database into the image, use image version 1.9.1--pyhdfd78af_0
@evezeyl can you look at that when you have time?

**Comment by hkaspersen** [comment]
Database version 5.0, https://zenodo.org/records/7669534

**Comment by evezeyl** [comment]
ok something I did not think about, not sure dockerhub will accept an image that is that big (33G) but can try. Anyway I will do the receipe and test. 
- [ ] if cannot host on docker hub need to find solution (try first)
note: wget https://zenodo.org/records/7669534/files/db.tar.gz?download=1

**Comment by evezeyl** [comment]
- image: docker://evezeyl/bakta:1.9.1
- database path in image: /home/db 
Will download and test in singularity now, and will add the docker recipie in assets for achive when I am sure its seems ok. (then we have that).  
I am not sure that it is a good solution, because the database is huge. If docker hub complains, we can see if its possible to make an account and push it in biocontainers maybe.

**Comment by evezeyl** [comment]
ok - tested the singularity image - so to use it path to put in nf is /bakta_db/db

**Comment by hkaspersen** [comment]
Confirmed working with the image.
However, the image is very large and takes a lot of time to download. Given the CI test need to download a fresh image every time this will significantly increase the runtime of the test, which we want to avoid. To alleviate this I suggest we merge the smaller database with the image instead of the full database. I have also added an optional parameter for users to supply their own path to their database, which can be used.
